### ISSUE TITLE
RuntimeError when trying to use the viewer

### ISSUE THREAD

**Issue by Kanazawanaoaki** [iory/scikit-robot#277]
RuntimeError occurred when I tried to use the viewer as follows.
```
$ python3
>>> import skrobot
>>> viewer = skrobot.viewers.TrimeshSceneViewer()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kanazawa/.local/lib/python3.8/site-packages/skrobot/viewers/__init__.py", line 9, in __init__
    raise RuntimeError('TrimeshSceneViewer cannot be initialized. '
RuntimeError: TrimeshSceneViewer cannot be initialized. This issue happens when the X window system is not running.
```
I understand that it is in the exception handling here https://github.com/iory/scikit-robot/blob/7c09772f95028b818442475b3a26bc3eed0ff289/skrobot/viewers/__init__.py#L3-L11, but how can I avoid the error?  

I believe that the X Windows System is running because I can check the operation with `xeyes`.

**Comment by Kanazawanaoaki** [comment]
This problem was solved when I did the following.
```
pip3 install "pyglet<2"
```

The reason I did this was because I got the following log while trying.
```
>>> import trimesh.viewer
>>> type(trimesh.viewer.SceneViewer())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kanazawa/.local/lib/python3.8/site-packages/trimesh/exceptions.py", line 48, in failed
    raise exc
  File "/home/kanazawa/.local/lib/python3.8/site-packages/trimesh/viewer/__init__.py", line 18, in <module>
    from .windowed import (SceneViewer,
  File "/home/kanazawa/.local/lib/python3.8/site-packages/trimesh/viewer/windowed.py", line 20, in <module>
    raise ImportError('`trimesh.viewer.windowed` requires `pip install "pyglet<2"`')
ImportError: `trimesh.viewer.windowed` requires `pip install "pyglet<2"`
```

**Comment by HiroIshida** [comment]
Actually, this problem is not solved, as reported in https://github.com/iory/scikit-robot/issues/272
As I reported in the issue, the poblem happens only when you install from pypi. (For source local install it seems ok)

Because, in setup.py pyglet version is specified, the pyglet < 2.0 is supposed to be installed 
https://github.com/iory/scikit-robot/blob/7c09772f95028b818442475b3a26bc3eed0ff289/setup.py#L51
